# Generated by Django 2.0.3 on 2018-05-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('CAT', 'cat'), ('DOG', 'dog'), ('BIRD', 'bird'), ('COW', 'cow'), ('GOAT', 'goat'), ('SNAKE', 'snake')], max_length=5)),
                ('type_of_breed', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('colour', models.CharField(max_length=30)),
                ('behaivour', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Cats',
            },
        ),
    ]
