# Generated by Django 2.0.3 on 2018-05-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name_plural': 'Pets'},
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='behaivour',
            new_name='behaviour',
        ),
    ]
