# Generated by Django 2.0.3 on 2018-05-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20180503_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.CharField(default='', max_length=30),
        ),
    ]
