# Generated by Django 2.0.3 on 2018-05-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_auto_20180503_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('CAT', 'cat'), ('DOG', 'dog'), ('BIRD', 'bird'), ('COW', 'cow'), ('GOAT', 'goat'), ('REPTILE', 'reptile'), ('PIG', 'pig')], max_length=5),
        ),
    ]
